### ISSUE TITLE
Might not need `lib` folder

### ISSUE THREAD

**Issue by mmahalwy** [quran/common-components#5]
I know the lib folder was the compiled code but since we will just import the components directly from other projects, no need, no? 

For example

`import Button from '@quran/common-components/src/components/Button;`

Thoughts?

**Comment by thabti** [comment]
@mmahalwy I tried this and it wouldn't work if I didn't compile the code via babel. I have remove it from the repo and it is generated on the CI. I will make `src/components` available via NPM and you can try. 

Basically it was complaining about ES6 `import`, I think it might be due to us excluding `node_modules` in webpack. We do server side rendering too.

**Comment by mmahalwy** [comment]
+1 good point

**Comment by thabti** [comment]
any idea how we get react-storybook to show the prop details like: [React-date](http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) ?

click top right question mark.

**Comment by mmahalwy** [comment]
https://github.com/quran/common-components/pull/10 adds it :)

**Comment by thabti** [comment]
thanks bro! loving react-storybook.

**Comment by mmahalwy** [comment]
likewise :)
